// Native Save dialog for score exports (Tauri desktop). Plain-browser
// downloads (`<a download>`) silently drop into the WebKitGTK process cwd in
// the packaged desktop app — there is no way for a user to discover where
// the file went. This module routes the export through the OS-native save
// dialog instead, when running inside Tauri.
//
// Permission/scope handshake (verified against the installed crate source,
// not just docs): `tauri-plugin-dialog`'s `save` command, once the user
// picks a path, calls `window.try_fs_scope().allow_file(&path)` before
// returning it (tauri-plugin-dialog-2.7.2/src/commands.rs, `save()`). That
// dynamically extends the fs plugin's scope to that exact file for the rest
// of the session — so the capability only needs `dialog:allow-save` (to
// invoke the dialog) and `fs:allow-write-file` (to invoke the write
// command); no static fs scope/directory permission is required, since the
// dialog plugin grants the one path itself at runtime.
//
// The two plugin imports are dynamic and kept INSIDE the isTauri() branch
// so the plain-browser bundle (e.g. `npm run dev` outside the Tauri
// shell, or a future web build) never evaluates `@tauri-apps/plugin-*`,
// which assume a Tauri IPC bridge is present.

import { isTauri as isTauriRuntime } from "@tauri-apps/api/core";

export function isTauri(): boolean {
  return isTauriRuntime();
}

export type SaveExportResult = "saved" | "cancelled" | "fallback";

/**
 * Fetches `url`, then offers the bytes to the user via a native Save
 * dialog (Tauri) with `suggestedName` pre-filled. Outside Tauri, this is a
 * deliberate no-op that returns "fallback" — the caller is expected to keep
 * its existing `<a download>` behavior in that case.
 */
export async function saveExport(url: string, suggestedName: string): Promise<SaveExportResult> {
  if (!isTauri()) {
    return "fallback";
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Export download failed: ${response.status} ${response.statusText}`);
  }
  const bytes = new Uint8Array(await response.arrayBuffer());

  return saveBytesViaDialog(bytes, suggestedName);
}

/** Shared by `saveExport` (server-fetched bytes) and `savePdfBytes`
 * (client-generated bytes) -- both end the same way once bytes are in
 * hand: open the native Save dialog, `writeFile` the chosen path (or
 * report "cancelled" if the user dismissed the dialog). Only called on
 * the Tauri branch by both callers, so it doesn't re-check `isTauri()`
 * itself.
 *
 * `writeFile` (binary) rather than `writeTextFile` -- confirmed against
 * the installed `@tauri-apps/plugin-fs` 2.5.1 typings: `writeFile(path,
 * contents: Uint8Array, options?)` is the binary-safe write;
 * `writeTextFile` takes a `string` and would corrupt non-UTF-8 bytes like
 * a PDF's binary body (MusicXML/MIDI already relied on `writeFile` here
 * too, for MIDI's sake -- PDF just confirms the same choice is correct).
 */
async function saveBytesViaDialog(bytes: Uint8Array, suggestedName: string): Promise<SaveExportResult> {
  const [{ save }, { writeFile }] = await Promise.all([
    import("@tauri-apps/plugin-dialog"),
    import("@tauri-apps/plugin-fs"),
  ]);

  const extension = suggestedName.includes(".") ? suggestedName.split(".").pop() ?? "" : "";
  const destination = await save({
    defaultPath: suggestedName,
    filters: extension ? [{ name: extension.toUpperCase(), extensions: [extension] }] : [],
  });

  if (destination === null) {
    return "cancelled";
  }

  await writeFile(destination, bytes);
  return "saved";
}

/**
 * Saves already-in-memory bytes (e.g. a client-generated PDF -- there is
 * no server URL to fetch, unlike `saveExport`) via the same native Save
 * dialog + `writeFile` path in Tauri.
 *
 * Outside Tauri, `saveExport`'s own fallback (leave the browser's native
 * `<a download>` to do the work) doesn't apply here -- a generated PDF
 * has no `href` for an anchor to point at. This performs the equivalent
 * plain-browser download itself: a `Blob` + a temporary `<a
 * download>`/`URL.createObjectURL` click, which every evergreen browser
 * treats as a normal user-initiated download. Still returns "fallback"
 * (not "saved") for the same reason `saveExport` does outside Tauri: no
 * native OS Save dialog was shown, just the browser's own download
 * mechanism.
 */
export async function savePdfBytes(bytes: Uint8Array, suggestedName: string): Promise<SaveExportResult> {
  if (!isTauri()) {
    downloadBlobInBrowser(bytes, suggestedName);
    return "fallback";
  }

  return saveBytesViaDialog(bytes, suggestedName);
}

/** How long to keep the object URL alive after the click before revoking
 * it. Revoking on the very next tick can race the browser's own (async)
 * download-start in some engines and cancel the download; this generous
 * delay is a well-known workaround (the anchor/blob itself is tiny -- the
 * actual write-to-disk happens on the OS side, not blocked on this). */
const OBJECT_URL_REVOKE_DELAY_MS = 1000;

/** Plain-browser download of in-memory bytes: a temporary, DOM-attached
 * `<a download>` pointed at a `Blob` object URL, clicked once. The anchor
 * is attached to the document (not just constructed) because some
 * browsers only honor a programmatic `.click()` on an anchor that is
 * actually in the DOM. */
function downloadBlobInBrowser(bytes: Uint8Array, suggestedName: string): void {
  // Cast needed: TypeScript's DOM lib types `BlobPart` as requiring a
  // concrete `ArrayBuffer`-backed view, while `Uint8Array` is generic over
  // `ArrayBufferLike` (which also covers `SharedArrayBuffer`) since
  // TS 5.7 -- a real `Uint8Array` (this one included; it's never backed by
  // a SharedArrayBuffer here) has always been a valid `BlobPart` at
  // runtime, this is a type-level-only mismatch.
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = suggestedName;
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(objectUrl), OBJECT_URL_REVOKE_DELAY_MS);
}
