fn main() {
  // `install_dependency` (src/install.rs) spawns a package-manager install
  // process -- a privileged action -- so it gets its own explicit,
  // autogenerated ACL permission (`allow-install-dependency`, referenced in
  // capabilities/default.json) rather than being left ungated. See
  // tauri-build 2.6.3's `AppManifest::commands` doc comment: this
  // autogenerates `./permissions/autogenerated/install_dependency.toml`
  // with `allow-install-dependency`/`deny-install-dependency` permission
  // identifiers, which `tauri_build::build()` (called via `try_build`
  // below) then globs up via the default `./permissions/**/*` pattern.
  tauri_build::try_build(
    tauri_build::Attributes::new()
      .app_manifest(tauri_build::AppManifest::new().commands(&["install_dependency"])),
  )
  .expect("failed to run tauri-build");
}
